"use client";
import { useState } from "react";
import { BellRing, Mail, Send, ShieldAlert, Users } from "lucide-react";
import type { SchoolReport } from "@/lib/portal/institutions";

export function CoordinatorClient({ school, reports }: { school: string | null; reports: SchoolReport[] }) {
  const classes = reports.flatMap((r) => r.classes);
  const [classId, setClassId] = useState(classes.length === 1 ? classes[0].id : ""); const [title, setTitle] = useState(""); const [message, setMessage] = useState("");
  const [email, setEmail] = useState(true); const [notice, setNotice] = useState(false); const [busy, setBusy] = useState(false); const [result, setResult] = useState("");
  async function send() { setBusy(true); setResult(""); try { const r = await fetch("/api/portal/coordinator/communicate", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ classId: classId || undefined, title, message, sendEmail: email, notice }) }); const j = await r.json(); if (!r.ok) throw new Error(j.error || "Could not send."); setResult(`Sent to ${j.recipients} student${j.recipients === 1 ? "" : "s"}${email ? `; ${j.emails} email recipient(s).` : "."}`); setTitle(""); setMessage(""); } catch (e) { setResult((e as Error).message); } finally { setBusy(false); } }
  return <div className="space-y-6">
    <div><h1 className="font-display text-2xl text-ice">Class staff desk</h1><p className="text-sm text-dust">{school ? `${school} · restricted to your assigned class${classes.length === 1 ? "" : "es"}.` : "Administrator view across all schools."}</p></div>
    <div className="grid grid-cols-2 gap-3 sm:grid-cols-4">{[["Students", reports.reduce((n, s) => n + s.students, 0)], ["Active", reports.reduce((n,s)=>n+s.activeStudents,0)], ["Attempts", reports.reduce((n,s)=>n+s.totalAttempts,0)], ["Classes", classes.length]].map(([l,v]) => <div key={String(l)} className="rounded-xl border border-white/10 bg-space/60 p-3"><p className="text-[10px] uppercase tracking-widest text-dust">{l}</p><p className="font-display text-xl text-cyan">{v}</p></div>)}</div>
    <section className="rounded-2xl border border-white/10 bg-space/60 p-5"><div className="flex items-center gap-2"><BellRing size={17} className="text-cyan" /><h2 className="font-display text-lg text-ice">Announcement, message or show-cause notice</h2></div><p className="mt-1 text-xs text-dust">Creates an in-portal notification for one assigned class. Optionally emails those students and their parent/guardian addresses.</p><div className="mt-4 grid gap-3"><select value={classId} onChange={(e)=>setClassId(e.target.value)} className="rounded-lg border border-white/10 bg-abyss px-3 py-2 text-sm text-ice"><option value="">Choose an assigned class…</option>{classes.map(c=><option key={c.id} value={c.id}>{c.name || `${c.year} ${c.section || ""}`}</option>)}</select><input value={title} onChange={(e)=>setTitle(e.target.value)} placeholder="Subject / announcement title" className="rounded-lg border border-white/10 bg-abyss px-3 py-2 text-sm text-ice"/><textarea value={message} onChange={(e)=>setMessage(e.target.value)} rows={4} placeholder="Write the message…" className="rounded-lg border border-white/10 bg-abyss px-3 py-2 text-sm text-ice"/><div className="flex flex-wrap gap-4 text-xs text-fog"><label><input type="checkbox" checked={email} onChange={(e)=>setEmail(e.target.checked)} /> <Mail className="inline" size={12}/> email student & parents</label><label><input type="checkbox" checked={notice} onChange={(e)=>setNotice(e.target.checked)} /> <ShieldAlert className="inline" size={12}/> show-cause notice</label></div><button disabled={busy || !classId || !title.trim() || !message.trim()} onClick={send} className="btn-primary w-fit !px-4 !py-2 text-sm"><Send size={14}/>{busy ? "Sending…" : "Send"}</button>{result ? <p className="text-xs text-cyan">{result}</p> : null}</div></section>
    <section className="space-y-4"><h2 className="flex items-center gap-2 font-display text-lg text-ice"><Users size={17} className="text-cyan"/> Students & progress</h2>{reports.map(s => <div key={s.school} className="rounded-2xl border border-white/10 bg-space/60 p-4"><h3 className="font-display text-base text-ice">{s.school}</h3>{s.classes.map(c=><div key={c.id} className="mt-3 overflow-x-auto"><p className="text-xs text-cyan">{c.name || `${c.year} ${c.section || ""}`}</p><table className="mt-1 w-full min-w-[520px] text-left text-xs"><thead className="text-dust"><tr><th>Student</th><th>Attendance</th><th>Accuracy</th><th>Attempts</th><th>Last active</th></tr></thead><tbody>{c.students.map(x=><tr key={x.uid} className="border-t border-white/10 text-fog"><td className="py-2">{x.name}</td><td>{x.attendancePct == null ? "—" : `${x.attendancePct}%`}</td><td>{x.accuracy == null ? "—" : `${x.accuracy}%`}</td><td>{x.attempts}</td><td>{x.lastActive ? new Date(x.lastActive).toLocaleDateString() : "never"}</td></tr>)}</tbody></table></div>)}</div>)}</section>
  </div>;
}
